# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

from dataclasses import dataclass

import torch
from online_draft.models.qwen3_eagle3 import (
    Qwen3Eagle3ForCausalLM,
)
from online_draft.training.eagle3_batch import (
    Eagle3DistillationBatch,
)


@dataclass(frozen=True, slots=True)
class Eagle3TrainingInputs:
    """Inputs for one parallel differentiable proposal canvas.

    All rows are evaluated in one causal forward. The first row is the
    proposal anchor. Later rows use recurrent hidden inputs generated by
    the GPU draft model and copied to the CPU.
    """

    positions: torch.Tensor
    input_embeds: torch.Tensor
    hidden_states: torch.Tensor
    teacher_probabilities: torch.Tensor
    rejection_position: int | None

    @property
    def draft_length(self) -> int:
        """Return the number of proposal prediction positions."""
        return self.positions.numel()


def prepare_eagle3_training_inputs(
    model: Qwen3Eagle3ForCausalLM,
    batch: Eagle3DistillationBatch,
) -> Eagle3TrainingInputs:
    """Prepare one parallel EAGLE3 training canvas.

    The anchor hidden input is recomputed through the trainable CPU FC
    layer. Every later hidden input was generated by the GPU draft model
    and is treated as fixed input. The CPU does not regenerate later
    recurrent hidden states token by token.

    This function does not construct or modify KV cache. The caller must
    provide a detached historical prefix cache ending immediately before
    the anchor position. KV created temporarily inside the canvas remains
    differentiable until the current backward finishes.

    Args:
        model: CPU EAGLE3 training model.
        batch: Prepared CPU tensors for one verification round.

    Returns:
        Inputs and targets for one parallel causal forward.

    Raises:
        ValueError: If the model and batch are incompatible.
    """
    feature_dtype = batch.prefill_input_embeds.dtype

    batch.validate(
        hidden_size=model.config.hidden_size,
        num_aux_hidden_states=model.config.num_aux_hidden_states,
        draft_vocab_size=model.config.draft_vocab_size,
        feature_dtype=feature_dtype,
    )

    model_device, model_dtype = _get_model_device_and_dtype(model)

    if model_device.type != "cpu":
        raise ValueError("EAGLE3 training model must be on the CPU")

    if model_dtype != feature_dtype:
        raise ValueError("batch feature dtype must match the model parameter dtype")

    # The proposal anchor is the final prefill input. Its persistent KV,
    # if present, must be excluded from the cache passed to this canvas.
    # Recomputing the anchor creates the first proposal logits and keeps
    # the anchor FC path differentiable.
    anchor_input_embeds = batch.prefill_input_embeds[-1:]
    anchor_aux_hidden_states = batch.prefill_aux_hidden_states[-1:]
    anchor_hidden_states = model.combine_hidden_states(anchor_aux_hidden_states)

    # These rows were generated during GPU draft inference and copied to
    # CPU as fixed training inputs. The CPU does not regenerate them from
    # preceding CPU model outputs.
    later_input_embeds = batch.draft_token_input_embeds
    later_hidden_states = batch.draft_recurrent_hidden_states

    # Causal attention preserves position dependencies even though all
    # proposal rows are submitted in one parallel model forward.
    input_embeds = torch.cat(
        (
            anchor_input_embeds,
            later_input_embeds,
        ),
        dim=0,
    )
    hidden_states = torch.cat(
        (
            anchor_hidden_states,
            later_hidden_states,
        ),
        dim=0,
    )

    if input_embeds.shape != hidden_states.shape:
        raise RuntimeError(
            "assembled input embeddings and hidden states must have the same shape"
        )

    if input_embeds.shape[0] != batch.draft_length:
        raise RuntimeError("assembled proposal inputs must match draft length")

    return Eagle3TrainingInputs(
        positions=batch.proposal_positions,
        input_embeds=input_embeds,
        hidden_states=hidden_states,
        teacher_probabilities=batch.teacher_probabilities,
        rejection_position=batch.rejection_position,
    )


def _get_model_device_and_dtype(
    model: Qwen3Eagle3ForCausalLM,
) -> tuple[torch.device, torch.dtype]:
    floating_parameters = [
        parameter for parameter in model.parameters() if parameter.is_floating_point()
    ]

    if not floating_parameters:
        raise ValueError("EAGLE3 model must contain floating-point parameters")

    devices = {parameter.device for parameter in floating_parameters}
    if len(devices) != 1:
        raise ValueError("all floating-point model parameters must use one device")

    dtypes = {parameter.dtype for parameter in floating_parameters}
    if len(dtypes) != 1:
        raise ValueError("all floating-point model parameters must use one dtype")

    return (
        floating_parameters[0].device,
        floating_parameters[0].dtype,
    )
