# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

from dataclasses import dataclass
from typing import TYPE_CHECKING

import torch
from online_draft.models.qwen3_eagle3 import (
    Qwen3Eagle3ForCausalLM,
)
from online_draft.training.eagle3_batch import (
    Eagle3DistillationBatch,
)

if TYPE_CHECKING:
    from online_draft.training.eagle3_window import (
        Eagle3TrainingWindow,
    )


@dataclass(frozen=True, slots=True)
class Eagle3TrainingInputs:
    """Inputs for one parallel differentiable proposal canvas.

    All rows are evaluated in one causal forward. The first row is the
    proposal anchor. Later rows use recurrent hidden inputs generated by
    the GPU draft model and copied to the CPU.
    """

    positions: torch.Tensor
    input_embeds: torch.Tensor
    hidden_states: torch.Tensor
    teacher_probabilities: torch.Tensor
    rejection_position: int | None

    @property
    def draft_length(self) -> int:
        """Return the number of proposal prediction positions."""
        return self.positions.numel()


@dataclass(frozen=True, slots=True)
class Eagle3ConfirmedPathInputs:
    """Packed confirmed query rows and their isolated attention mask.

    Every row has a distillation target. Each round starts with an anchor
    recomputed through the trainable FC path. Later rows use fixed recurrent
    hidden states captured while the GPU generated that draft branch.
    """

    positions: torch.Tensor
    input_embeds: torch.Tensor
    hidden_states: torch.Tensor
    attention_mask: torch.Tensor
    teacher_probabilities: torch.Tensor
    rejection_target_mask: torch.Tensor

    @property
    def input_length(self) -> int:
        """Return the number of packed confirmed query rows."""
        return self.positions.numel()

    @property
    def target_count(self) -> int:
        """Return the number of confirmed-path targets."""
        return self.teacher_probabilities.shape[0]


@dataclass(frozen=True, slots=True)
class Eagle3ProposalWindowInputs:
    """Packed proposal branches and their isolated attention mask.

    Every input row has a distillation target. In the boolean attention
    mask, True blocks a query-key pair and False makes it visible.
    """

    positions: torch.Tensor
    input_embeds: torch.Tensor
    hidden_states: torch.Tensor
    attention_mask: torch.Tensor
    teacher_probabilities: torch.Tensor
    rejection_target_mask: torch.Tensor

    @property
    def input_length(self) -> int:
        """Return the number of packed proposal rows."""
        return self.positions.numel()

    @property
    def target_count(self) -> int:
        """Return the number of proposal targets."""
        return self.teacher_probabilities.shape[0]


@dataclass(frozen=True, slots=True)
class _Eagle3PackedWindowInputs:
    """Internal tensors shared by the two packed window objectives."""

    positions: torch.Tensor
    input_embeds: torch.Tensor
    hidden_states: torch.Tensor
    attention_mask: torch.Tensor
    teacher_probabilities: torch.Tensor
    rejection_target_mask: torch.Tensor


def prepare_eagle3_training_inputs(
    model: Qwen3Eagle3ForCausalLM,
    batch: Eagle3DistillationBatch,
) -> Eagle3TrainingInputs:
    """Prepare one parallel EAGLE3 training canvas.

    The anchor hidden input is recomputed through the trainable CPU FC
    layer. Every later hidden input was generated by the GPU draft model
    and is treated as fixed input. The CPU does not regenerate later
    recurrent hidden states token by token.

    This function does not construct or modify KV cache. The caller must
    provide a detached historical prefix cache ending immediately before
    the anchor position. KV created temporarily inside the canvas remains
    differentiable until the current backward finishes.

    Args:
        model: CPU EAGLE3 training model.
        batch: Prepared CPU tensors for one verification round.

    Returns:
        Inputs and targets for one parallel causal forward.

    Raises:
        ValueError: If the model and batch are incompatible.
    """
    feature_dtype = batch.prefill_input_embeds.dtype

    batch.validate(
        hidden_size=model.config.hidden_size,
        num_aux_hidden_states=model.config.num_aux_hidden_states,
        draft_vocab_size=model.config.draft_vocab_size,
        feature_dtype=feature_dtype,
    )

    model_device, model_dtype = _get_model_device_and_dtype(model)

    if model_device.type != "cpu":
        raise ValueError("EAGLE3 training model must be on the CPU")

    if model_dtype != feature_dtype:
        raise ValueError("batch feature dtype must match the model parameter dtype")

    # The proposal anchor is the final prefill input. Its persistent KV,
    # if present, must be excluded from the cache passed to this canvas.
    # Recomputing the anchor creates the first proposal logits and keeps
    # the anchor FC path differentiable.
    anchor_input_embeds = batch.prefill_input_embeds[-1:]
    anchor_aux_hidden_states = batch.prefill_aux_hidden_states[-1:]
    anchor_hidden_states = model.combine_hidden_states(anchor_aux_hidden_states)

    # These rows were generated during GPU draft inference and copied to
    # CPU as fixed training inputs. The CPU does not regenerate them from
    # preceding CPU model outputs.
    later_input_embeds = batch.draft_token_input_embeds
    later_hidden_states = batch.draft_recurrent_hidden_states

    # Causal attention preserves position dependencies even though all
    # proposal rows are submitted in one parallel model forward.
    input_embeds = torch.cat(
        (
            anchor_input_embeds,
            later_input_embeds,
        ),
        dim=0,
    )
    hidden_states = torch.cat(
        (
            anchor_hidden_states,
            later_hidden_states,
        ),
        dim=0,
    )

    if input_embeds.shape != hidden_states.shape:
        raise RuntimeError(
            "assembled input embeddings and hidden states must have the same shape"
        )

    if input_embeds.shape[0] != batch.draft_length:
        raise RuntimeError("assembled proposal inputs must match draft length")

    return Eagle3TrainingInputs(
        positions=batch.proposal_positions,
        input_embeds=input_embeds,
        hidden_states=hidden_states,
        teacher_probabilities=batch.teacher_probabilities,
        rejection_position=batch.rejection_position,
    )


def prepare_eagle3_confirmed_path_inputs(
    model: Qwen3Eagle3ForCausalLM,
    window: "Eagle3TrainingWindow",
    *,
    spine_length: int,
) -> Eagle3ConfirmedPathInputs:
    """Pack only query rows whose targets are confirmed.

    A rejected round keeps rows through the rejection position, including
    the row trained against the correction target. A fully accepted round
    keeps all draft rows; its bonus has no prediction row or direct loss.
    Every round anchor goes through FC, while later rows retain the fixed
    recurrent hidden inputs captured from GPU draft generation.

    Args:
        model: CPU EAGLE3 training model.
        window: Consecutive verification rounds.
        spine_length: Length of the temporary full confirmed spine.

    Returns:
        Packed confirmed query branches, targets, and isolation mask.
    """
    target_counts = tuple(
        (
            round_batch.draft_length
            if round_batch.rejection_position is None
            else round_batch.confirmed_length
        )
        for round_batch in window.rounds
    )
    packed = _prepare_eagle3_packed_window_inputs(
        model,
        window,
        spine_length=spine_length,
        target_counts=target_counts,
        expected_target_count=window.confirmed_path_target_count,
    )

    return Eagle3ConfirmedPathInputs(
        positions=packed.positions,
        input_embeds=packed.input_embeds,
        hidden_states=packed.hidden_states,
        attention_mask=packed.attention_mask,
        teacher_probabilities=packed.teacher_probabilities,
        rejection_target_mask=packed.rejection_target_mask,
    )


def prepare_eagle3_proposal_window_inputs(
    model: Qwen3Eagle3ForCausalLM,
    window: "Eagle3TrainingWindow",
    *,
    spine_length: int,
) -> Eagle3ProposalWindowInputs:
    """Pack all proposal branches for one differentiable forward.

    Every branch sees confirmed spine positions strictly before its anchor
    and a causal prefix of only its own proposal rows. Other branches and
    future confirmed positions remain blocked.

    Args:
        model: CPU EAGLE3 training model.
        window: Consecutive verification rounds.
        spine_length: Length of the temporary full confirmed spine.

    Returns:
        Packed proposal inputs, targets, and branch-isolation mask.

    Raises:
        TypeError: If spine_length is not an integer.
        ValueError: If the spine or batch tensors are inconsistent.
    """
    target_counts = tuple(round_batch.draft_length for round_batch in window.rounds)
    packed = _prepare_eagle3_packed_window_inputs(
        model,
        window,
        spine_length=spine_length,
        target_counts=target_counts,
        expected_target_count=window.proposal_target_count,
    )

    return Eagle3ProposalWindowInputs(
        positions=packed.positions,
        input_embeds=packed.input_embeds,
        hidden_states=packed.hidden_states,
        attention_mask=packed.attention_mask,
        teacher_probabilities=packed.teacher_probabilities,
        rejection_target_mask=packed.rejection_target_mask,
    )


def _prepare_eagle3_packed_window_inputs(
    model: Qwen3Eagle3ForCausalLM,
    window: "Eagle3TrainingWindow",
    *,
    spine_length: int,
    target_counts: tuple[int, ...],
    expected_target_count: int,
) -> _Eagle3PackedWindowInputs:
    if isinstance(spine_length, bool) or not isinstance(spine_length, int):
        raise TypeError("spine_length must be an integer")

    expected_spine_length = window.end_confirmed_position + 1
    if spine_length != expected_spine_length:
        raise ValueError("window spine must end at the final confirmed position")

    if len(target_counts) != window.round_count:
        raise RuntimeError("every window round must have a target count")

    round_inputs = tuple(
        prepare_eagle3_training_inputs(model, round_batch)
        for round_batch in window.rounds
    )

    for inputs, target_count in zip(round_inputs, target_counts, strict=True):
        if not 1 <= target_count <= inputs.draft_length:
            raise ValueError("round target count must be within its draft length")

    total_query_length = sum(target_counts)
    positions = torch.cat(
        tuple(
            inputs.positions[:target_count]
            for inputs, target_count in zip(
                round_inputs,
                target_counts,
                strict=True,
            )
        ),
        dim=0,
    )
    input_embeds = torch.cat(
        tuple(
            inputs.input_embeds[:target_count]
            for inputs, target_count in zip(
                round_inputs,
                target_counts,
                strict=True,
            )
        ),
        dim=0,
    )
    hidden_states = torch.cat(
        tuple(
            inputs.hidden_states[:target_count]
            for inputs, target_count in zip(
                round_inputs,
                target_counts,
                strict=True,
            )
        ),
        dim=0,
    )
    teacher_probabilities = torch.cat(
        tuple(
            inputs.teacher_probabilities[:target_count]
            for inputs, target_count in zip(
                round_inputs,
                target_counts,
                strict=True,
            )
        ),
        dim=0,
    )

    attention_mask = torch.ones(
        (
            total_query_length,
            spine_length + total_query_length,
        ),
        dtype=torch.bool,
        device=positions.device,
    )
    rejection_target_mask = torch.zeros(
        total_query_length,
        dtype=torch.bool,
        device=positions.device,
    )

    query_start = 0
    for round_batch, inputs, target_count in zip(
        window.rounds,
        round_inputs,
        target_counts,
        strict=True,
    ):
        query_end = query_start + target_count
        anchor_position = int(inputs.positions[0].item())

        if not 0 <= anchor_position < spine_length:
            raise ValueError("window anchor must be inside the confirmed spine")

        # The detached spine already contains the anchor. Block that copy
        # and later spine entries so this branch uses its trainable anchor.
        attention_mask[query_start:query_end, :anchor_position] = False

        branch_causal_mask = torch.triu(
            torch.ones(
                target_count,
                target_count,
                dtype=torch.bool,
                device=positions.device,
            ),
            diagonal=1,
        )
        branch_key_start = spine_length + query_start
        branch_key_end = spine_length + query_end
        attention_mask[
            query_start:query_end,
            branch_key_start:branch_key_end,
        ] = branch_causal_mask

        rejection_position = round_batch.rejection_position
        if rejection_position is not None and rejection_position < target_count:
            rejection_target_mask[query_start + rejection_position] = True

        query_start = query_end

    if query_start != total_query_length:
        raise RuntimeError("packed window row count is inconsistent")
    if total_query_length != expected_target_count:
        raise RuntimeError("packed target count does not match the window")

    return _Eagle3PackedWindowInputs(
        positions=positions,
        input_embeds=input_embeds,
        hidden_states=hidden_states,
        attention_mask=attention_mask,
        teacher_probabilities=teacher_probabilities,
        rejection_target_mask=rejection_target_mask,
    )


def _get_model_device_and_dtype(
    model: Qwen3Eagle3ForCausalLM,
) -> tuple[torch.device, torch.dtype]:
    floating_parameters = [
        parameter for parameter in model.parameters() if parameter.is_floating_point()
    ]

    if not floating_parameters:
        raise ValueError("EAGLE3 model must contain floating-point parameters")

    devices = {parameter.device for parameter in floating_parameters}
    if len(devices) != 1:
        raise ValueError("all floating-point model parameters must use one device")

    dtypes = {parameter.dtype for parameter in floating_parameters}
    if len(dtypes) != 1:
        raise ValueError("all floating-point model parameters must use one dtype")

    return (
        floating_parameters[0].device,
        floating_parameters[0].dtype,
    )
